name: Daily Crawler

on:
  schedule:
       - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: crawler
        run: pip install -r requirements.txt

      - name: Write .env
        run: |
          echo "${{ secrets.ENV_FILE }}" > backend/.env

      - name: Run crawler
        working-directory: crawler
        run: python main.py
